
package com.example.consumeWS.demo.wsdl;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CarrosPort", targetNamespace = "http://spring.io.carros2-jar-maven-ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarrosPort {


    /**
     * 
     * @param getMarcaRequest
     * @return
     *     returns com.example.consumeWS.demo.wsdl.GetMarcaResponse
     */
    @WebMethod
    @WebResult(name = "getMarcaResponse", targetNamespace = "http://spring.io.carros2-jar-maven-ws", partName = "getMarcaResponse")
    public GetMarcaResponse getMarca(
        @WebParam(name = "getMarcaRequest", targetNamespace = "http://spring.io.carros2-jar-maven-ws", partName = "getMarcaRequest")
        GetMarcaRequest getMarcaRequest);

    /**
     * 
     * @param setCarroRequest
     */
    @WebMethod
    @Oneway
    public void setCarro(
        @WebParam(name = "setCarroRequest", targetNamespace = "http://spring.io.carros2-jar-maven-ws", partName = "setCarroRequest")
        SetCarroRequest setCarroRequest);

}
