
package com.example.consumeWS.demo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CarrosPortService", targetNamespace = "http://spring.io.carros2-jar-maven-ws", wsdlLocation = "http://localhost:8080/ws/carros.wsdl")
public class CarrosPortService
    extends Service
{

    private final static URL CARROSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARROSPORTSERVICE_EXCEPTION;
    private final static QName CARROSPORTSERVICE_QNAME = new QName("http://spring.io.carros2-jar-maven-ws", "CarrosPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/carros.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARROSPORTSERVICE_WSDL_LOCATION = url;
        CARROSPORTSERVICE_EXCEPTION = e;
    }

    public CarrosPortService() {
        super(__getWsdlLocation(), CARROSPORTSERVICE_QNAME);
    }

    public CarrosPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARROSPORTSERVICE_QNAME, features);
    }

    public CarrosPortService(URL wsdlLocation) {
        super(wsdlLocation, CARROSPORTSERVICE_QNAME);
    }

    public CarrosPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARROSPORTSERVICE_QNAME, features);
    }

    public CarrosPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarrosPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarrosPort
     */
    @WebEndpoint(name = "CarrosPortSoap11")
    public CarrosPort getCarrosPortSoap11() {
        return super.getPort(new QName("http://spring.io.carros2-jar-maven-ws", "CarrosPortSoap11"), CarrosPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarrosPort
     */
    @WebEndpoint(name = "CarrosPortSoap11")
    public CarrosPort getCarrosPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.io.carros2-jar-maven-ws", "CarrosPortSoap11"), CarrosPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARROSPORTSERVICE_EXCEPTION!= null) {
            throw CARROSPORTSERVICE_EXCEPTION;
        }
        return CARROSPORTSERVICE_WSDL_LOCATION;
    }

}
